# Base configs
baseurl: "https://i.navnee.tk/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
# google_analytics: ""

# UI configs
title: "Photography by Navneethakrishnan"
subtitle: "My photography collection"
author: "Navneethakrishnan"
header:
 title: "Photography"
 subtitle: "by Navneet"
footer:
 name: "Hey there, my name is Navneet"
 bio: "Amateur Photographer, Software Consultant/Linux SysAdmin, Football Fanatic"
web_design: "By AJ and Jekylled by Ram Patra"
social_urls:
  instagram: "https://www.instagram.com/nav.kris"
  dribbble: "https://dribbble.com/navneethakrishnan"
  linkedin: "https://in.linkedin.com/in/navneethakrishnan"
  github: "https://www.github.com/navneet-suresh"
