# Base configs
baseurl: "https://ddraffft.in"
siteurl: "/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Navneethakrishnan"
subtitle: "My photography collection"
author: "Navneethakrishnan"
header:
 title: "Photography"
 subtitle: "by Navneethakrishnan"
footer:
 name: "Hey there, my name is Navneet"
 bio: "Autodidact, Photographer, SysAdmin, Football Fanatic.."
web_design: "By AJ"
social_urls:
  facebook: "https://www.facebook.com/clickme.dng"
  twitter: "https://www.twitter.com/clickme_exe"
  instagram: "https://www.instagram.com/clickme.sh"
  dribbble: "https://dribbble.com/"
  linkedin: "https://in.linkedin.com/in/"
  github: "https://www.github.com/navneet-suresh"
